- src/index.js
- src/internals/helpers.js
- src/yupSchema.js
- feat: Export helper methods `pickXKey` and `buildCompleteYupSchema`
These two helpers `pickXKey` and `buildCompleteYupSchema` may be useful for the users (it's useful for us at Remote).
> feat: Export util methods `pickXKey` and `buildCompleteYupSchema`

- json-schema-form.schema.json
- package.json
Pretty nice stuff you made here.
I was missing some type annotations for those custom `x-jsf-` properties, so I wrote some.
I hope there isn't already a definition I overlooked?
> feat: added json-schema-form meta schema

- .eslintignore
- json-schema-form.d.ts
- package-lock.json
- package.json
- src/createHeadlessForm.js
Add a declaration file giving some types to the 3 exported functions that the library has.
* `createHeadlessForm`
* `pickXKey`
* `buildCompleteYupSchema`
Some arguments are generic to be able to ship something fast, I think if we need better types, we'll need to spend more time on it.
## 2. How to test this
I created a next app with typescript in my local environment and copied the content of this [codesandbox](https://codesandbox.io/s/json-schema-form-demo-react-igh3sk?from-embed), after doing that, I installed a release dev version, the one I used is 0.1.1-dev.20230616085129 to test that everything work as expected.
> feat: Add Typescript declarations

- package-lock.json
- package.json
- src/helpers.js
- src/tests/createHeadlessForm.test.js
- src/yupSchema.js
Add a transform function to make the validation work when we're passing numbers or booleans to our text validation.
https://www.loom.com/share/b7a127623c5b41e78d6d3f2d21fcba59?focus_title=1&muted=1&from_recorder=1
- https://linear.app/remote/issue/RMT-446/jsf-text-validation-is-incorrect
> fix(text-validation) - pass only values that are strings

- src/helpers.js
- src/tests/createHeadlessForm.test.js
- src/tests/helpers.js
For example, given the following JSON Schema, where each `oneOf` contains a `x-jsf-presentation`:
```js
{
properties: {
health_perks: {
title: 'Health perks',
oneOf: [
{
const: 'basic',
title: 'Basic',
'x-jsf-presentation': {
cost: '$30.00/mo',
},
'x-another': 'extra-thing',
},
{
const: 'standard',
title: 'Standard',
'x-jsf-presentation': {
cost: '$50.00/mo',
},
}
],
'x-jsf-presentation': {
inputType: 'radio',
layout: "vertical"
},
type: 'string',
},
},
}
```
Without this PR, to access the `cost` of each option, you'd need to do:
``` js
const { fields } = createHeadlessForm(demoAbove);
const cost = fields[0].options[0]['x-jsf-presentation'].cost
```
Now, you can access it directly with:
```js
const cost = fields[0].options[0].displayCost
```
In other words, now we move the …
> feat(Radio/Select): Spread x-jsf-presentation value to option root

- package-lock.json
- package.json
- src/checkIfConditionMatches.js
- src/helpers.js
- src/tests/checkIfConditionMatches.test.js
- src/tests/conditions.test.js
Internal conversation https://remote-com.slack.com/archives/C02HTN0LY02/p1691493090023339
When we have a if check that needs to check two levels deep, it would break the `json-schema-form` library, this adds a check to `checkIfConditionMatches` to make it more capable to do understand these property types.
Theres enough logic to justify its own file, and I started some dedicated tests.
> Allow deeply nested if property checks

- package-lock.json
- package.json
- src/createHeadlessForm.js
- src/helpers.js
- src/jsonLogic.js
- src/tests/jsonLogic.fixtures.js
- src/tests/jsonLogic.test.js
- src/tests/jsonLogicFixtures.js
- src/yupSchema.js
This is a breakdown of https://github.com/remoteoss/json-schema-form/pull/28 to make it more digestible for review.
There will be multiple PRs:
- Adding JSON Logic's skeleton, with basic support for `x-jsf-logic-validations`. That is this PR.
- Add in `x-jsf-logic-computedAttrs` (with reference to values defined in `x-jsf-logic.computedValues`) support.
- General error handling. 
- Fieldset support
- Conditional handling
- Inline rules for `x-jsf-logic-computedAttrs` support.
This PR:
- Adds the JSON Logic library.
- Sets up the plumbing of json-logic's implementation in a JSON schema to work on different object levels (the scopes).
- Adds the plumbing to use JSON logic during the runtime of a `json-schema-form` instance in `createHeadlessForm.js`
- Adds the logic to apply this at the yup …
> [JSON Logic] Part 1: JSON Logic Skeleton

- src/tests/createHeadlessForm.test.js
- src/tests/helpers.js
- src/yupSchema.js
Add oneOf pattern validation.
- If the options in a oneOf contain a value, validation remains the same as it currently is.
- If the options contain a regex pattern, use that to test the value.
How:
- Update `radioOrSelect` yup schema
- Add test
> fix(select/radio): Support oneOf[].pattern validation

- package-lock.json
- package.json
- src/helpers.js
- src/tests/conditions.test.js
Follow-up of #57, adds `Component` and `calculateDynamicProperties` as one of the attrs to be ignored during conditional attributes.
> chore(hotfix): Ignore internal attributes from conditional attributes removal

- src/tests/createHeadlessForm.test.js
- src/tests/helpers.js
- src/yupSchema.js
This PR removes the logic added in https://github.com/remoteoss/json-schema-form/pull/54 for we will no longer be using this approach.
> fix(select): Remove creatable logic

- json-schema-form.d.ts
- src/index.js
- src/modify.js
- src/tests/modify.test.js
Note: This PR is heavily inspired by [this pull request](https://github.com/remoteoss/json-schema-form/pull/71) that will be divided into smaller PRs.
Currently, doing customizations to JSON Schemas is quite fragile and we don't have any specs to allow it.
Move JSON Schema customizations to happen before the schema is parsed.
- Before: createHeadlessForm() (with customizations) → Form output
- Proposal: customizations → createHeadlessForm() → Form output
This reduces the complexity inside createHeadlessForm(), solving existing limitations and bugs.
Additionally it has a clear separation of concerns “customizations VS parsing”
```
// Before:
const form = createHeadlessForm(jsonSchema, {
customProperties: { 
my_field: {
description: "My new description."
}
}
); 
// New:
const newSchema = …
```
> Create modify() utility for better customizations

- src/modify.js
- src/tests/modify.test.js
Follow-up of https://github.com/remoteoss/json-schema-form/pull/75, with a new fix.
[Linear issue (internal)](https://linear.app/remote/issue/PBYR-1372)
This one was tough, I caught it while adopting `modify()` in our internal Remote codebase, check this out:
Imagine the giving JSON Schema:
```js
{
properties: {
has_pet: {
title: 'Has Pet',
oneOf: [
{ title: 'Yes', const: 'yes' },
{ title: 'No', const: 'no' },
],
'x-jsf-presentation': {
inputType: 'radio',
},
type: 'string',
},
},
};
```
And you want to customize the `has_pet` options to be just one option saying "Nop":
```js
modify(schemaPet, {
fields: {
has_pet: {
oneOf: [{ const: "nop", title: "Nop" }]
}
},
});
```
The `merge()` does not override arrays, it merges them based on the index, so the result would still contain the original …
> fix(modify): Customize attrs as Array now overrides the value

- .eslintrc
- src/modify.js
- src/tests/modify.test.js
Follow-up of https://github.com/remoteoss/json-schema-form/pull/71, scoped on customizing the order of fields.
This MR can only be merged after #83 
[Linear issue (internal)](https://linear.app/remote/issue/PBYR-1363)
Imagine the schema below with 4 fields:
```js
{
properties: {
/* does not matter */
},
'x-jsf-order': ['field_a', 'field_b', 'field_c', 'field_d'],
};
```
To reorder the fields, pass the given config:
```js
const result = modify(schema, {
orderRoot: ['field_d', 'field_c', 'field_a', 'field_b',];
});
```
The new order will be: `['field_d', 'field_c', 'field_a', 'field_b',];`.
You also have access to the original order using a callback:
```js
const result = modify(baseExample, {
orderRoot: (original) => original.reverse(),
});
```
The new order will be  `['field_d', 'field_c', …
> feat(modify): Allow customize fields order

- src/modify.js
- src/tests/modify.test.js
Follow-up of https://github.com/remoteoss/json-schema-form/pull/71, scoped on allowing to add new fields
[Linear issue (internal)](https://linear.app/remote/issue/EXPM-631)
Imagine the schema with 2 fields:
```js
const baseSchema = {
properties: {
age: {
title: 'Age',
type: 'integer',
},
family_name: {
title: 'Family Name',
type: 'string',
}
},
'x-jsf-order': ['age', 'family_name'],
};
```
If you want to add a new field to the JSON Schema pass the following config:
```js
const { schema }  = modify(baseSchema, {
create: {
username: {
title: 'Username',
type: 'string',
},
}
)
```
Which will return the schema:
```js
{
properties: {
age: {
title: 'Age',
type: 'integer',
},
family_name: {
title: 'Family Name',
type: 'string',
},
username: {
title: 'Username',
type: 'string',
}
}, …
```
> feat(modify): Allow creating fields

- src/modify.js
- src/tests/modify.test.js
Follow-up of https://github.com/remoteoss/json-schema-form/pull/75, but now also allowing to customize `x-jsf-presentation` more easily with just `presentation`:
[Linear issue (internal)](https://linear.app/remote/issue/RMT-777)
```js
modify(schemaPet, {
fields: {
pet_age: {
'x-jsf-presentation': {
'data-foo': 123,
},
}
},
});
```
```js
modify(schemaPet, {
fields: {
pet_age: {
presentation: {
'data-foo': 123,
},
},
},
});
```
> feat(modify): Add x-jsf-presentation shorthand

- src/tests/createHeadlessForm.test.js
chore(tests): Move code in global test scope to inside beforeAll
When we need to run only a specific test (`it.only()`), we were seeing logs of `createHeadlessForm()` outside that test unit. That can cause a lot of noise if we want to debug only a specific unit test, but also seeing logs from other instances.
That happens because we had 1 instance of `createHeadlessForm()` being called outside jest lifecycle.
Moved that 1 instance in the global scope (inside `describe()`) to an isolated scope, using `beforeAll()`
A simple way can be to add `console.log()` to inside the `createHeadlessForm()`
```diff
export function createHeadlessForm(jsonSchema, customConfig = {}) {
+  console.log('Hello!')
```
And then run only one test at your choise. Eg  `it.only('returns empty result given no schema'` …
> chore(tests): Move code in global test scope to inside beforeAll

- src/helpers.js
- src/internals/checkIfConditionMatches.js
- src/jsonLogic.js
- src/tests/checkIfConditionMatches.test.js
- src/tests/conditions.test.js
- src/tests/createHeadlessForm.customValidations.test.js
- src/tests/createHeadlessForm.test.js
- src/tests/utils.test.jsx
As the name says, I slightly improved the tests organization. I time-boxed ~30m for this. What I did:
- Added new `describe()`s.
- Marked which tests are about deprecated features (not meant to be in v2)
- Some minor reorders.
- Migrated some `JSONSchemaBuilder` to normal JSON Schemas, but not all, it was more than 50. I'll leave that for another MR.
What I did not do:
- Refactors to tests logic, otherwise it's a mess.
- I did not create new files, it would be harder to track the changes. 
Yet, even with these efforts, the code review is barely impossible. How can you trust me?
The nr of tests between `main` and this PR is 1 less test. (now it's 278) I deleted the test `pass "description" to field` because it was redundant compared to the tests `supports both root level "description"`. …
> chore(tests): Slightly better tests organization

- src/tests/conditions.test.js
I've added a few tests highlighting existing bugs in JSF. For awareness and to make sure they get solved when the next major version is developed:
* c525914 - multiple conditionals to the same field are not applied 
* 0403f72 - values passed to handleValidation are mutated, but should not 
* e232aba - conditional hidden fields should throw an error, but they do not
[Internal ticket](https://linear.app/remote/issue/DEVXP-2535)
> chore(conditionals): Highlight bugs related to validations and conditional fields 

- .gitmodules
- next/test/validation/json_schema_test_suite.test.ts
This adds the json schema test suite repo as a submodule and defines a test for each test case from the test suite dynamically.
> DEVXP-2603: chore(next): use json schema test suite

- next/src/types.ts
- next/src/validation/anyOf.ts
- next/src/validation/schema.ts
- next/test/validation/anyOf.test.ts
This PR add handling for the `anyOf` keyword. Also includes the tests from the [official test suite](https://github.com/json-schema-org/JSON-Schema-Test-Suite/blob/main/tests/draft2020-12/anyOf.json) as well as a test with a demo schema.
> DEVXP-2544: feat(next): add `anyOf` validation

- next/.gitignore
- next/eslint.config.mjs
- next/jest.config.mjs
- next/package.json
- next/pnpm-lock.yaml
- next/src/form.ts
- next/src/validation/anyOf.ts
- next/src/validation/format.ts
- next/src/validation/object.ts
- next/src/validation/schema.ts
- next/src/validation/string.ts
- next/test/validation/boolean_schema.test.ts
- next/test/validation/format.test.ts
- next/test/validation/object.test.ts
- next/test/validation/string.test.ts
This PR applies a couple suggestions from [this previous PR](https://github.com/remoteoss/json-schema-form/pull/128), thanks @thien-remote.
Changes are:
- adds a new package `validator` to make the validations better in `format.ts`
- uses the `Format` enum from the `json-schema-typed` package instead of our custom solution (again in `format.ts)
- adjusts the way we handle the `path` key across the package - now matching the way we do it in the original package
- some minor changes, adding comments and tests
> DEVXP-XXX: handle paths

- next/test/json-schema-test-suite/failed-json-schema-test-suite.json
- next/test/json-schema-test-suite/helpers.ts
- next/test/json-schema-test-suite/json-schema-test-suite-tracker.js
- next/test/json-schema-test-suite/json-schema-test-suite.test.ts
Now the tests from the [official json-schema suite ](https://github.com/json-schema-org/JSON-Schema-Test-Suite/tree/main/tests/draft2020-12) that we should temporarily ignore are better organized.
See screenshot of new JSON structure below:
> chore: refactor ignored tests structure

- src/jsonLogic.js
- src/tests/jsonLogic.fixtures.js
- src/tests/jsonLogic.test.js
This was a bug brought up internally when trying to create a schema similar to the test case. This is because of a false assumption on my side where I didn't need to account for "temp variables" that are indeed supported in json logic for cases like `reduce`.
> chore(json-logic): Add skipped broken unit test for missing json-logic `reduce` support

- next/src/validation/composition.ts
- next/test/validation/composition.test.ts
Quick PR to fix the `anyOf` error message. This got left out from the [previous PR](https://github.com/remoteoss/json-schema-form/pull/145).
> fix(next): match `anyOf` and `oneOf` error messages

- next/src/errors/index.ts
- next/src/errors/messages.ts
- next/src/form.ts
- next/src/validation/composition.ts
- next/src/validation/conditions.ts
- next/src/validation/const.ts
- next/src/validation/enum.ts
- next/src/validation/format.ts
- next/src/validation/number.ts
- next/src/validation/object.ts
- next/src/validation/schema.ts
- next/src/validation/string.ts
- next/test/errors/messages.test.ts
- next/test/json-schema-test-suite/failed-json-schema-test-suite.json
- next/test/validation/composition.test.ts
- next/test/validation/enum.test.ts
- next/test/validation/format.test.ts
- next/test/validation/number.test.ts
This PR centralizes generating error messages.
1. `message` is removed from the `ValidationError` interface.
1. There is a new `addErrorMessages` function that 
1. `path` in the `ValidationError` interface now includes the full path to a subschema when a composition keyword like e.g. `anyOf` is used.
This is needed to look up a schema & value pair in `addErrorMessages` given a path.
> chore(next): DEVXP-2682: centralize error messages

- next/src/form.ts
- next/src/validation/schema.ts
- next/test/errors/messages.test.ts
- next/test/json-schema-test-suite/failed-json-schema-test-suite.json
This addresses a bug where validation errors in conditional schemas would not generate correct error messages.
Check out the added tests for concrete examples.
> fix(next): RMT-1405: fix error messages for conditional schemas

- next/package.json
- next/src/form.ts
- next/src/validation/schema.ts
- next/src/visibility.ts
- next/test/visibility.test.ts
- next/tsup.config.js
This MR aims to fix some of the problems our _visibility_ calculation had, which happened when evaluating conditional (inside an `if/then/else` statement) visibility of fields inside a `fieldset`:
- tests were added to `visibility.test.ts` to highlight the main behavior we should implement
- a fix was added, and the main logic is:
- fields are visible by default
- a field is not visible if a schema for that field is has a `false` boolean value
Some quality of life improvements:
- a `dev` script that runs `tsup` in watch mode
- this script also sets an env variable that disables minification in the final build. This makes setting breakpoints in the consumer app way easier 🤓
> fix(next): DEVXP-2802: add some simple unit tests that highlight the wrong visibility behavior

- next/src/types.ts
- next/src/utils.ts
- next/src/validation/composition.ts
- next/src/validation/schema.ts
- next/src/visibility.ts
- next/test/utils.test.ts
- next/test/visibility.test.ts
- Added proper type safety for `required` fields in JSON Schema type
- With this change I was able to simplify some conditional checks across validation and visibility logic
- Added new utility function `getField` for safer field access (Based on suggetion from https://github.com/remoteoss/json-schema-form/pull/152)
- Improved test readability using the new `getField` utility and added tests for the new utility function
> chore: add getField util and improve json-schema-form schema type

- next/src/errors/messages.ts
- next/test/errors/messages.test.ts
Fixes two minor inconsistencies
* Unchecked, required checkboxes generate a `Please acknowledge this field` error instead of `Required field`
* `const` validation error messages end with a `.`, i.e. `The only accepted value is 1.`
> chore(v1): validation error message fixes

- src/tests/createHeadlessForm.test.js
- src/tests/helpers.custom.js
- src/tests/helpers.js
This changes all test helpers to use `x-jsf-presentation` instead of the deprecated `presentation` so that they can be used with the next version.
> chore: change deprecated `presentation` to `x-jsf-presentation` in test helpers

- next/src/errors/index.ts
- next/src/errors/messages.ts
- next/src/validation/custom/date.ts
- next/src/validation/schema.ts
- next/test/errors/messages.test.ts
- Added date validation support with `minDate` and `maxDate` constraints on the `x-jsf-presentation` property
- Added custom date format validation messages
- Added new error types for date validation
- Added test coverage for date validation scenarios
```typescript
const schema = {
type: 'string',
format: 'date',
'x-jsf-presentation': {
minDate: '2022-01-01',
maxDate: '2022-12-31'
}
}
```
- Invalid format: "Must be a valid date in yyyy-mm-dd format. e.g. 2024-03-21"
- Min date violation: "The date must be 2022-01-01 or after."
- Max date violation: "The date must be 2022-12-31 or before."
> feat(next): Add date validation

- next/src/field/object.ts
- next/test/fields.test.ts
- Added support for `description` field in JSON Schema objects
- The description field is now properly parsed and included in the form field metadata
- Updated tests to verify description handling
> fix: include description when building fieldset Field

- next/src/modify-schema.ts
- next/test/modify-schema.test.ts
Adds a couple return type description to functions and adds the `@types/lodash` package to the dev dependencies.
> chore(next): fix linter and type checker warnings

- next/src/errors/index.ts
- next/src/errors/messages.ts
- next/src/utils.ts
- next/src/validation/file.ts
- next/src/validation/schema.ts
- next/test/validation/file.test.ts
This PR adds the missing file validation. This is not really related to json schema in general but more just something that we support with jsf. 
The goal was to mimic what we do in v0 and to make the failing tests pass.
> feat(next): implement file validation

- next/package.json
Correcting the version number for `next` as we already have a `beta.2` version released on NPM. 
It was released 3 months ago so it was probably done while we setup the release process. 
This PR corrects the version number in the `package.json` so we can start releasing `beta` versions normally.
> fix(next): version number

- next/src/mutations.ts
- next/src/types.ts
- next/src/validation/array.ts
- next/src/validation/composition.ts
- next/src/validation/conditions.ts
- next/src/validation/json-logic.ts
- next/src/validation/object.ts
- next/src/validation/schema.ts
- next/test/validation/json-logic.test.ts
This PR adds support for running schema validations on a `x-jsf-logic` node.
(Most of the solution is on the changes in `src/validation/schema.ts` file. The rest of the changes are due to type renaming and adding new tests.
1. **Renaming / new types**:
- Renamed `JsonLogicBag` to `JsonLogicContext`
- Renamed `JsonLogicSchema` to `JsonLogicRules`
- Added new type `JsonLogicRootSchema` for schema validation rules
- Added new type `JsonLogicSchema` that combines `JsonLogicRules` and `JsonLogicRootSchema`
2. **Schema Validation Changes**:
- Enhanced `validateSchema` to handle both JSON Logic validations and schema validations from `x-jsf-logic`
- Split validation of `x-jsf-logic` into two parts:
- JSON Logic rules (validations/computedValues)
- Schema validation rules (if/then/else/allOf/etc) …
> feat(next): custom validations with json logic inner conditionals

- next/package.json
- next/src/errors/index.ts
- next/src/form.ts
- next/src/validation/array.ts
- next/src/validation/composition.ts
- next/src/validation/const.ts
- next/src/validation/custom/date.ts
- next/src/validation/enum.ts
- next/src/validation/file.ts
- next/src/validation/format.ts
- next/src/validation/json-logic.ts
- next/src/validation/number.ts
- next/src/validation/schema.ts
- next/src/validation/string.ts
- next/test/test-utils.ts
- next/test/validation/array.test.ts
- next/test/validation/composition.test.ts
- next/test/validation/enum.test.ts
- next/test/validation/file.test.ts
- next/test/validation/json-logic.test.ts
- next/test/validation/number.test.ts
- next/test/validation/optional.test.ts
Adds `schema` and `value` to `ValidationError`, allowing for the validators to pass extra context to the next step (message interpolation). It also removes the need for traversing the schema an extra time to calculate the correct context for each error message. 
This is why there are a lot of changes: I had to go through each validator and pass these 2 extra properties and update every test that was asserting on the errors returned by the `validateSchema` call.
- Added `schema` and `value` fields to `ValidationError` interface to track the schema and value that caused the validation error
- Removed `getSchemaAndValueAtPath` function since schema and value are now directly available in the error object
- Simplified `addErrorMessages` function to use the schema and value directly from the …
> chore: refactor error message interpolation approach

- next/src/field/schema.ts
- next/test/fields.test.ts
- next/test/validation/boolean_type.test.ts
Our previous implementation had a bug:
- it only populated `checkboxValue` if the schema had a `const` and had `checkbox` as its input type
This is a problem because it's not taking into account the `type` of the schema. In other words, to mimic v0's behavior, one should set the `checkboxValue` to either what's defined in the `const` property OR to boolean, in case the `type` is `boolean`.
Added 2 groups of tests
- one for boolean validation (not boolean schemas, but schemas of type boolean)
- one for the `fields` generation
> fix(v1): use correct checkboxValue on checkbox inputs

- next/src/types.ts
- next/src/validation/json-logic.ts
- next/src/validation/schema.ts
- next/src/validation/util.ts
- next/test/validation/json-logic.test.ts
1. Renamed and improved core functions:
- `validateJsonLogic` → `validateJsonLogicRules` for better clarity
- `replaceUndefinedValuesWithNulls` → `replaceUndefinedAndNullValuesWithNaN` which reflects better what the function does
2. Added support for computed attributes:
- New function `validateJsonLogicComputedAttributes` to handle dynamic schema attributes
- added dedicated test suite under `json-logic.test.ts`
3. Better type definitions with `SchemaValue` and `ValidationOptions`
> feat(next): support for json-logic (part 2)

- next/src/validation/json-logic.ts
- next/test/validation/json-logic.test.ts
Small PR, ensuring our json-logic module throws Errors at the same point the v0 version does, updating tests accordingly.
> feat: throw on invalid json-logic schemas

- next/src/field/schema.ts
- next/src/field/type.ts
- next/test/fields.test.ts
Sets the `jsonType` property on fields correctly. It should just be what the actual schema's type is.
> fix(next): set field jsonType to the schema's type

- next/src/types.ts
Follow-up of https://github.com/remoteoss/json-schema-form/pull/181, comment https://github.com/remoteoss/json-schema-form/pull/181#discussion_r2073595996. 
Watch this [loom](https://www.loom.com/share/15db241248f44ea4af0cfcc2b6f1428b) explaining why `enum` should be typed as `unknown[]` instead of `any[]`.
TLDR: Internally we use `enum` to map it to some places that must be `string`. By using `any`, TS doesn't throw an error saying `enum` is not a `string`, which can lead to bugs if we don't pay attention (shown in Loom). 
By typing `enum` as `unknown[]`, TS calls our attention to it.
> chore(next): Type JSONSchema enum as unknown for better type safety

- next/src/mutations.ts
- next/test/fields/mutation.test.ts
This fixes a bug in next where the `required` property on a field was not updated when the field's required status changes through a conditional schema.
I've added a test that illustrates the issue.
> fix(next): update required property on fields when it is changed through conditional schemas

- next/src/validation/schema.ts
- next/test/validation/boolean_schema.test.ts
This adds an option that allow passing values to `false` schemas. This would normally result in a validation error but in v0 we explicitly clear values provided to a false schema: https://github.com/remoteoss/json-schema-form/blob/4efb07e3cd27a2e0a79b704e57e12432c80310f2/src/helpers.js#L451-L461
This option will achieve the same goal, but in a more straight forward way. It will also be disabled by default.
> feat(next): add allowForbiddenValues validation option

- next/src/validation/composition.ts
- next/test/json-schema-test-suite/failed-json-schema-test-suite.json
- next/test/validation/composition.test.ts
As it turns out, `{"oneOf": []}` should match any value. Previously we would just return a validation error in this case, but I think that's not correct. I think [the spec](https://json-schema.org/draft/2020-12/json-schema-core#section-10.2.1.3) can be interpreted either way but matching any value seems more practical to me and this is also how v0 handles it.
> fix(v1): don't fail validation when oneOf array is empty

- MIGRATING.md
Improve migration process docs
> chore: improve migration doc

- MIGRATING.md
- src/form.ts
- src/index.ts
- src/mutations.ts
- src/validation/array.ts
- src/validation/composition.ts
- src/validation/conditions.ts
- src/validation/custom/date.ts
- src/validation/object.ts
- src/validation/schema.ts
- test/errors/messages.test.ts
- test/form.test.ts
Follow-up of https://github.com/remoteoss/json-schema-form/pull/211, comment:
> note: Now looking back I'd have called this v0Support instead of ValidationOptions. This is where we'd also pass any config to still support deprecated features.
> 
> Another one that comes to my mind is [dropping type attr in favor of of inputType](https://linear.app/remote/issue/DEVXP-2862/deprecate-type-attr-on-field). If we have done that already, then it would look like this:
> ```js
> const form = createHeadlessForm(schema, {
>   v0Support: {
>       includeTypeAttr: true,
>   }
> }
> ```
> fix: rename validationOptions to legacyOptions

- src/field/schema.ts
- src/form.ts
- src/validation/util.ts
- test/fields.test.ts
- test/fields/array.test.ts
- test/form.test.ts
We had a bug where custom field properties that are not serializable (eg functions) were being left out in the final output. This PR fixes it.
> fix: properly handle function as custom field properties

- CHANGELOG.md
- package.json
- scripts/release.js
Improve release scripts to remove duplicated prefixes, add check for bump types and generating changelog for official releases
> chore: improve release scripts

- scripts/release.js
An old prefix that was appended to the git tag (`1-official`) was breaking the logic for bumping versions. This fix uses the `semver` lib to clean unnecessary info and use the correct version to serve as basis for the bump
> chore: strip down old version prefixes that were used (1-official)

- scripts/release.js
Fixes issues where changelog updates were only done for beta releases (it should also happen for _official_ releases)
> fix: update changelog on non-dev release

- scripts/release.js
When fetching the git tags for bumping versions, we should use the date as the sort mechanism, not the version refname
> fix: use commiter date as sorting order for tags, not version

- src/errors/index.ts
- src/errors/messages.ts
- src/field/schema.ts
- src/validation/composition.ts
- test/errors/messages.test.ts
- test/validation/composition.test.ts
The current `anyOf` implementation has 2 issues:
- visually it breaks the form, as it wrongly interprets root anyOf as if it belonged to a select or checkbox group options
- the error message is a string with a stringified json object which is wrong. It should target individual fields with issues, and not treat the anyOf as a single error.
This MR addresses it by:
- not adding `options` if the field is the root
- returning the actual failed validations for each field when an `anyOf` is not valid
> fix: anyof condition breaking UI 

- scripts/release.js
- src/validation/json-logic.ts
- test/validation/json-logic.test.ts
Refactors the `cycleThroughAttrsAndApplyValues` implementation on `json-logic` with a more recursive-ish logic so that properties nested on `allOf`/`anyOf`/`oneOf` definitions are also parsed when `x-jsf-logic-computedAttrs` are resolved.
For instance, given the following property:
```
'temperature_setting': {
'title': 'Select a preset temperature',
'type': 'string',
'oneOf': [
{
'title': 'Low',
'const': 18,
},
{
'title': 'Medium',
'const': 20,
},
{
'title': 'Maximum',
'x-jsf-logic-computedAttrs': {
'const': 'maximum_temperature',
},
},
],
},
```
the `const` on the last item of the property's `oneOf` will be properly parsed with the computed value.
Also fixes the `dev` version release script.
> feat(json-logic): apply computed attrs on nested allOf/anyOf/oneOf properties

- src/errors/index.ts
- src/errors/messages.ts
- src/validation/schema.ts
- test/validation/additional_properties.test.ts
A JSON Schema with `additionalProperties: false` is meant to disallow properties not declared in the JSON Schema! 
This adds the validation based on that option
> fix(schema): additionalProperties not working

- src/field/schema.ts
- test/fields.test.ts
Spreads all `x-jsf-presentation` properties inside a radio option's schema into the option's final representation, instead of just picking the `meta` key.
This maintains the `v1` feature parity by implementing the same behaviour as `v0` (https://github.com/remoteoss/json-schema-form/pull/17)
> fix(options): spread all option's presentation properties into option's root
